### ISSUE TITLE
error in compiling with php 7.3.33 ZTS

### ISSUE THREAD

**Issue by cryptobob** [sjinks/php-disable-eval#60]
/bin/sh /usr/local/src/php-disable-eval/libtool --mode=compile cc  -I. -I/usr/local/src/php-disable-eval -DPHP_ATOM_INC -I/usr/local/src/php-disable-eval/include -I/usr/local/src/php-disable-eval/main -I/usr/local/src/php-disable-eval -I/usr/include/php-zts/php -I/usr/include/php-zts/php/main -I/usr/include/php-zts/php/TSRM -I/usr/include/php-zts/php/Zend -I/usr/include/php-zts/php/ext -I/usr/include/php-zts/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/src/php-disable-eval/disable-eval.c -o disable-eval.lo 
libtool: compile:  cc -I. -I/usr/local/src/php-disable-eval -DPHP_ATOM_INC -I/usr/local/src/php-disable-eval/include -I/usr/local/src/php-disable-eval/main -I/usr/local/src/php-disable-eval -I/usr/include/php-zts/php -I/usr/include/php-zts/php/main -I/usr/include/php-zts/php/TSRM -I/usr/include/php-zts/php/Zend -I/usr/include/php-zts/php/ext -I/usr/include/php-zts/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/src/php-disable-eval/disable-eval.c  -fPIC -DPIC -o .libs/disable-eval.o
/usr/local/src/php-disable-eval/disable-eval.c: In function 'zend_compile_string_override':
/usr/local/src/php-disable-eval/disable-eval.c:150:9: error: initializer element is not constant
         { ZEND_STRL(" : eval()'d code"),            "eval()",                           &DE_G(enabled)      },
         ^
/usr/local/src/php-disable-eval/disable-eval.c:150:9: error: (near initialization for 'patterns[0].check')
/usr/local/src/php-disable-eval/disable-eval.c:152:9: error: initializer element is not constant
         { ZEND_STRL(" : runtime-created function"), "create_function()",                &DE_G(enabled)      },
         ^
/usr/local/src/php-disable-eval/disable-eval.c:152:9: error: (near initialization for 'patterns[1].check')
/usr/local/src/php-disable-eval/disable-eval.c:153:9: error: initializer element is not constant
         { ZEND_STRL(" : assert code"),              "assert() with a string argument",  &DE_G(watch_assert) },
         ^
/usr/local/src/php-disable-eval/disable-eval.c:153:9: error: (near initialization for 'patterns[2].check')
/usr/local/src/php-disable-eval/disable-eval.c:154:9: error: initializer element is not constant
         { ZEND_STRL(" : mbregex replace"),          "mb_ereg_replace() with 'e' flag",  &DE_G(enabled)      },
         ^
/usr/local/src/php-disable-eval/disable-eval.c:154:9: error: (near initialization for 'patterns[3].check')
make: *** [disable-eval.lo] Error 1

**Comment by sjinks** [comment]
What compiler (name and version) are you using?

**Comment by cryptobob** [comment]
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by sjinks** [comment]
OK, could you please try the most recent version?
